const ui={status:document.querySelector("#system-status"),guidedButton:document.querySelector("#run-guided-demo"),guidedResult:document.querySelector("#guided-result"),compileButton:document.querySelector("#compile-button"),compilerReport:document.querySelector("#compiler-report"),policySource:document.querySelector("#policy-source"),verifyButton:document.querySelector("#verify-button"),proofResult:document.querySelector("#proof-result"),rolloutButton:document.querySelector("#run-rollout-button"),rolloutResult:document.querySelector("#rollout-result"),runButton:document.querySelector("#run-attack-button"),comparison:document.querySelector("#comparison-board"),executionReceipt:document.querySelector("#execution-receipt"),approvalConsole:document.querySelector("#approval-console"),delegationButton:document.querySelector("#run-delegation-button"),delegationResult:document.querySelector("#delegation-result"),refundButton:document.querySelector("#run-refund-button"),refundResult:document.querySelector("#refund-result"),judgeButton:document.querySelector("#run-judge-button"),judgeResult:document.querySelector("#judge-result"),evaluationButton:document.querySelector("#run-evaluation-button"),evaluationResult:document.querySelector("#evaluation-result"),boundaryButton:document.querySelector("#run-boundary-button"),campaignResult:document.querySelector("#campaign-result"),availableBudget:document.querySelector("#available-budget"),availableAmount:document.querySelector("#available-amount"),reservedAmount:document.querySelector("#reserved-amount"),committedAmount:document.querySelector("#committed-amount"),budgetProgress:document.querySelector("#budget-progress"),auditList:document.querySelector("#audit-list"),eventCount:document.querySelector("#event-count"),auditButton:document.querySelector("#verify-audit-button"),evidenceButton:document.querySelector("#download-evidence-button"),auditIntegrity:document.querySelector("#audit-integrity"),toast:document.querySelector("#toast")};
let activeApprovalFlow=null;let activeRuntimePolicy=null;let activeJudgeScorecard=null;
const inPaise=rupees=>Math.round(Number(rupees)*100);
const inRupees=paise=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:paise%100===0?0:2}).format(paise/100);

function readPolicy(prefix="ui-runtime"){
  const monthly=inPaise(document.querySelector("#monthly-limit").value);
  const transaction=inPaise(document.querySelector("#transaction-limit").value);
  const threshold=inPaise(document.querySelector("#approval-threshold").value);
  const hours=Number(document.querySelector("#window-hours").value);
  if(transaction>monthly)throw new Error("Per-transaction limit cannot exceed the monthly budget.");
  if(threshold>monthly)throw new Error("Approval threshold cannot exceed the monthly budget.");
  return{policy_id:`${prefix}-${Date.now()}`,version:1,name:"Autonomous Procurement",currency:"INR",budget:{monthly_limit:monthly,per_transaction_limit:transaction},approval:{required_above:threshold,approver_count:1},vendors:{require_approved_vendor:true,allowed_vendor_ids:["vector-systems"],allowed_categories:["hardware"]},correlation:{window_hours:hours,group_by:["vendor","purpose"]}};
}

function paymentAction(runId,sequence){return{action_id:`${runId}-payment-${sequence}`,agent_id:"procurement-agent",amount:900000,vendor_id:"vector-systems",category:"hardware",purpose:"office-laptops",invoice_id:`${runId}-invoice-${sequence}`,approval_ids:[]}}
async function api(path,options={}){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const body=await response.json();if(!response.ok)throw new Error(body.detail||`Request failed with status ${response.status}`);return body}
function setBusy(button,busy,label){if(!button.dataset.label)button.dataset.label=button.innerHTML;button.disabled=busy;button.setAttribute("aria-busy",String(busy));button.innerHTML=busy?label:button.dataset.label}
function showToast(message,error=false){ui.toast.textContent=message;ui.toast.classList.toggle("error",error);ui.toast.classList.add("visible");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>ui.toast.classList.remove("visible"),3600)}

async function runGuidedDemo(){document.querySelector("#guided-demo").scrollIntoView({behavior:"smooth",block:"start"});setBusy(ui.guidedButton,true,"Running complete evidence path…");ui.guidedResult.innerHTML=`<div class="guided-loading"><span class="radar" aria-hidden="true"><span></span></span><strong>Evaluating the unsafe sequence and independent scorecard…</strong></div>`;try{const report=await api("/api/v1/demo/guided-run",{method:"POST"});const steps=report.steps.map(step=>`<article class="guided-step"><div class="guided-step-number">0${step.sequence}</div><div><small>${inRupees(step.amount)} · correlated ${inRupees(step.correlated_amount)}</small><h3>${step.finding}</h3><div class="guided-decisions"><span>Local gateway <strong class="decision ${decisionClass(step.naive_decision)}">${decisionLabel(step.naive_decision)}</strong></span><span>ArthaNiyam <strong class="decision ${decisionClass(step.arthaniyam_decision)}">${decisionLabel(step.arthaniyam_decision)}</strong></span></div><code>${step.reason_code}</code></div></article>`).join("");ui.guidedResult.innerHTML=`<div class="guided-story"><div><span class="panel-kicker">The problem</span><p>${report.problem}</p></div><div><span class="panel-kicker">The insight</span><p>${report.insight}</p></div></div><div class="guided-steps">${steps}</div><div class="guided-proof"><div><small>Outcome</small><strong>Unsafe sequence blocked</strong></div><div><small>Independent scorecard</small><strong>${report.scorecard_checks} checks · ${report.scorecard_test_cases} cases</strong></div><div><small>Canonical evidence</small><code>${report.evidence_hash}</code><span>Demo ${report.demo_id}</span></div><a class="button button-secondary" href="#evaluation-lab">Inspect full evidence</a></div>`;ui.guidedResult.focus({preventScroll:true});showToast(`Guided demo complete: ${report.scorecard_checks} checks across ${report.scorecard_test_cases} cases.`)}catch(error){ui.guidedResult.innerHTML=`<div class="guided-error"><strong>Demo could not complete.</strong><span>${error.message}</span></div>`;ui.guidedResult.focus({preventScroll:true});showToast(error.message,true)}finally{setBusy(ui.guidedButton,false)}}

async function checkHealth(){try{await api("/health");ui.status.classList.add("online");ui.status.querySelector("span:last-child").textContent="Runtime online"}catch{ui.status.classList.add("offline");ui.status.querySelector("span:last-child").textContent="Runtime offline"}}

async function runAuditIntegrity(){if(!activeRuntimePolicy)return;setBusy(ui.auditButton,true,"Verifying…");try{const report=await api(`/api/v1/runtime/policies/${encodeURIComponent(activeRuntimePolicy.policy_id)}/audit-integrity?version=${activeRuntimePolicy.version}`);ui.auditIntegrity.className=`audit-integrity ${report.valid?"verified":"broken"}`;ui.auditIntegrity.innerHTML=report.valid?`<strong>✓ Chain verified</strong><span>${report.chained_events} events · ${report.head_hash}</span>`:`<strong>Chain integrity failed at sequence ${report.first_broken_sequence}</strong><span>${report.issues.join(" · ")}</span>`;showToast(report.valid?"Audit chain verified.":"Audit chain integrity failure detected.",!report.valid)}catch(error){showToast(error.message,true)}finally{setBusy(ui.auditButton,false)}}

async function downloadAuditEvidence(){if(!activeRuntimePolicy)return;setBusy(ui.evidenceButton,true,"Exporting…");try{const bundle=await api(`/api/v1/runtime/policies/${encodeURIComponent(activeRuntimePolicy.policy_id)}/evidence-bundle?version=${activeRuntimePolicy.version}`);const blob=new Blob([JSON.stringify(bundle,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`arthaniyam-evidence-${activeRuntimePolicy.policy_id}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);showToast(`Evidence bundle exported: ${bundle.bundle_hash.slice(0,24)}…`)}catch(error){showToast(error.message,true)}finally{setBusy(ui.evidenceButton,false)}}

async function runPolicyRollout(){setBusy(ui.rolloutButton,true,"Replaying policy worlds…");try{const runId=`rollout-${Date.now()}`;const current=readPolicy(`${runId}-current`);const candidate=JSON.parse(JSON.stringify(current));candidate.policy_id=`${runId}-candidate`;candidate.version=2;candidate.name="Candidate autonomous procurement";candidate.approval.required_above=inPaise(document.querySelector("#candidate-threshold").value);if(candidate.approval.required_above>candidate.budget.monthly_limit)throw new Error("Candidate threshold cannot exceed the monthly budget.");const historical=[[1,900000,"laptops"],[2,700000,"chairs"],[3,850000,"monitors"]].map(([sequence,amount,purpose])=>({action_id:`${runId}-history-${sequence}`,agent_id:"procurement-agent",amount,vendor_id:"vector-systems",category:"hardware",purpose,invoice_id:`${runId}-history-invoice-${sequence}`,approval_ids:[]}));const report=await api("/api/v1/policies/impact/simulate",{method:"POST",body:JSON.stringify({current_policy:current,candidate_policy:candidate,actions:historical})});const rows=report.impacts.map(impact=>`<div class="rollout-row ${impact.changed?"changed":"unchanged"}"><div><small>${impact.action_id.split("-").slice(-2).join(" ")}</small><strong>${inRupees(impact.amount)}</strong></div><span class="decision ${decisionClass(impact.current_decision)}">${impact.current_decision}</span><span class="rollout-arrow">→</span><span class="decision ${decisionClass(impact.candidate_decision)}">${impact.candidate_decision}</span><code>${impact.candidate_reason_codes[0]}</code></div>`).join("");ui.rolloutResult.innerHTML=`<div class="rollout-summary"><div><small>New reviews</small><strong>${report.new_reviews}</strong></div><div><small>New denials</small><strong>${report.new_denials}</strong></div><div><small>Escalated actions</small><strong>${report.escalated_actions}</strong></div><div><small>Candidate reserved</small><strong>${inRupees(report.candidate_final_state.reserved_amount)}</strong></div></div><div class="rollout-rows">${rows}</div><div class="campaign-evidence"><code>${report.evidence_hash}</code><span>Simulation ${report.simulation_id}</span></div>`;showToast(`Policy impact: ${report.escalated_actions} actions escalated, ${report.new_denials} newly denied.`)}catch(error){showToast(error.message,true)}finally{setBusy(ui.rolloutButton,false)}}

async function compilePolicy(){setBusy(ui.compileButton,true,"Compiling constrained policy…");try{const result=await api("/api/v1/policies/compile",{method:"POST",body:JSON.stringify({policy_id:`ui-compiled-${Date.now()}`,version:1,source_text:ui.policySource.value})});renderCompilation(result);showToast(result.status==="ready_for_verification"?"Policy compiled and ready for verification.":"Policy needs review before verification.",result.status!=="ready_for_verification")}catch(error){showToast(error.message,true)}finally{setBusy(ui.compileButton,false)}}
function renderCompilation(result){const blockers=result.issues.filter(issue=>issue.severity==="blocker");const warnings=result.issues.filter(issue=>issue.severity==="warning");ui.compilerReport.className=`compiler-report ${result.status}`;ui.compilerReport.innerHTML=`<small>${result.compiler_mode} compiler · ${result.source_map.length} sourced rules</small><strong>${result.status.replaceAll("_"," ")}</strong><span>${blockers.length} blockers · ${warnings.length} warnings · ${result.assumptions.length} assumptions</span>${result.issues.length?`<ul>${result.issues.map(issue=>`<li class="${issue.severity}">${issue.message}</li>`).join("")}</ul>`:""}`;if(!result.policy)return;document.querySelector("#monthly-limit").value=result.policy.budget.monthly_limit/100;document.querySelector("#transaction-limit").value=result.policy.budget.per_transaction_limit/100;document.querySelector("#approval-threshold").value=result.policy.approval.required_above/100;document.querySelector("#window-hours").value=result.policy.correlation.window_hours}

async function verifyPolicy(){setBusy(ui.verifyButton,true,"Searching bounded state space…");try{const result=await api("/api/v1/policies/verify",{method:"POST",body:JSON.stringify({policy:readPolicy("ui-proof"),max_actions:4})});renderProof(result);showToast("Counterexample search completed.")}catch(error){showToast(error.message,true)}finally{setBusy(ui.verifyButton,false)}}

function renderProof(result){
  if(!result.counterexample){ui.proofResult.innerHTML=`<div class="empty-state"><span class="panel-kicker">Bounded result</span><h3>No counterexample found.</h3><p>${result.limitation}</p>${proofEvidence(result)}</div>`;return}
  const attack=result.counterexample;
  const actions=attack.actions.map(action=>`<div class="proof-action"><small>Action ${action.sequence} · locally allowed</small><strong>${inRupees(action.amount)}</strong></div>`).join("");
  ui.proofResult.innerHTML=`<div class="proof-found"><div class="proof-status"><span class="panel-kicker">Solver result</span><span class="danger-chip">Counterexample found</span></div><h3>Approval splitting is possible.</h3><p>${attack.explanation}</p><div class="proof-actions">${actions}</div><div class="proof-total"><span>Correlated commitment</span><strong>${inRupees(attack.correlated_total)}</strong></div>${proofEvidence(result)}</div>`;
}

function proofEvidence(result){const digest=result.evidence_hash||"not recorded";return `<div class="proof-evidence"><div><small>Canonical evidence</small><code>${digest}</code><span>Replay ID ${result.proof_run_id} · bound ${result.checked_bound} actions</span></div><button class="button button-secondary proof-replay" type="button" data-replay-proof="${result.proof_run_id}">Replay proof</button></div><div class="proof-replay-status" aria-live="polite"></div>`}
async function replayProof(button){setBusy(button,true,"Replaying…");try{const replay=await api(`/api/v1/proofs/${encodeURIComponent(button.dataset.replayProof)}/replay`,{method:"POST"});const status=ui.proofResult.querySelector(".proof-replay-status");status.className=`proof-replay-status ${replay.status}`;status.textContent=replay.status==="verified"?"✓ Stored evidence is intact and the solver reproduced the same result.":"⚠ Replay mismatch detected. The stored evidence or result has changed.";showToast(replay.status==="verified"?"Proof replay verified.":"Proof replay mismatch detected.",replay.status!=="verified")}catch(error){showToast(error.message,true)}finally{setBusy(button,false)}}

async function runAttack(){
  setBusy(ui.runButton,true,"Evaluating sequence…");
  try{
    const runId=`run-${Date.now()}`;const policy=readPolicy(runId);activeRuntimePolicy=policy;ui.auditButton.disabled=false;ui.evidenceButton.disabled=false;
    const firstAction=paymentAction(runId,1);const secondAction=paymentAction(runId,2);
    const first=await api("/api/v1/runtime/evaluate",{method:"POST",body:JSON.stringify({policy,action:firstAction})});
    const second=await api("/api/v1/runtime/evaluate",{method:"POST",body:JSON.stringify({policy,action:secondAction})});
    const execution=await api("/api/v1/executions/orders",{method:"POST",body:JSON.stringify({policy_id:policy.policy_id,policy_version:1,action_id:first.action_id})});
    const confirmation=execution.order.mode==="simulate"
      ? await api("/api/v1/executions/confirm",{method:"POST",body:JSON.stringify({policy_id:policy.policy_id,policy_version:1,action_id:first.action_id,simulated_outcome:"success"})})
      : await confirmWithRazorpay(execution,policy,first.action_id);
    const state=await api(`/api/v1/runtime/policies/${encodeURIComponent(policy.policy_id)}/state?version=1`);
    renderComparison([first,second]);renderExecution(execution,confirmation);renderRuntime(state,policy.budget.monthly_limit);
    if(second.arthaniyam.decision==="require_approval"&&execution.order.mode==="simulate"){const challenge=await api("/api/v1/demo/approvals/challenges",{method:"POST",body:JSON.stringify({policy_id:policy.policy_id,policy_version:1,action_id:second.action_id})});activeApprovalFlow={policy,action:secondAction,first,challenge};renderApprovalChallenge(challenge)}else if(second.arthaniyam.decision==="require_approval"){activeApprovalFlow=null;ui.approvalConsole.innerHTML=`<span class="receipt-icon">!</span><div><small>External approval required</small><strong>Test Mode requires an authenticated approver integration.</strong></div><code>secure boundary</code>`}
    showToast("First payment committed; correlated second payment is gated.");
  }catch(error){showToast(error.message,true)}finally{setBusy(ui.runButton,false)}
}

function renderApprovalChallenge(challenge){ui.approvalConsole.className="approval-console active";ui.approvalConsole.innerHTML=`<span class="receipt-icon">⌁</span><div><small>Exact-action challenge · expires ${new Date(challenge.expires_at).toLocaleTimeString("en-IN")}</small><strong>Review ${inRupees(challenge.amount)} to ${challenge.vendor_id} for ${challenge.purpose}</strong><span>${challenge.binding_hash.slice(0,28)}…</span></div><button class="button approval-button" type="button" data-approve-challenge="${challenge.challenge_id}">Simulate finance approval</button>`}
async function approveChallenge(button){if(!activeApprovalFlow)return;setBusy(button,true,"Approving…");try{const challenge=await api(`/api/v1/demo/approvals/challenges/${encodeURIComponent(button.dataset.approveChallenge)}/decide`,{method:"POST",body:JSON.stringify({approver_id:"finance-controller-demo",decision:"approve"})});if(challenge.status!=="approved")throw new Error("The required approver quorum has not been reached.");const approvedAction={...activeApprovalFlow.action,approval_ids:challenge.grants.map(grant=>grant.approval_id)};const approved=await api("/api/v1/runtime/evaluate",{method:"POST",body:JSON.stringify({policy:activeApprovalFlow.policy,action:approvedAction})});const execution=await api("/api/v1/executions/orders",{method:"POST",body:JSON.stringify({policy_id:activeApprovalFlow.policy.policy_id,policy_version:1,action_id:approved.action_id})});const confirmation=await api("/api/v1/executions/confirm",{method:"POST",body:JSON.stringify({policy_id:activeApprovalFlow.policy.policy_id,policy_version:1,action_id:approved.action_id,simulated_outcome:"success"})});const state=await api(`/api/v1/runtime/policies/${encodeURIComponent(activeApprovalFlow.policy.policy_id)}/state?version=1`);renderComparison([activeApprovalFlow.first,approved]);renderExecution(execution,confirmation);renderRuntime(state,activeApprovalFlow.policy.budget.monthly_limit);ui.approvalConsole.className="approval-console approved";ui.approvalConsole.innerHTML=`<span class="receipt-icon">✓</span><div><small>Approval consumed</small><strong>${challenge.grants[0].approver_id} approved the exact bound action.</strong><span>The grant cannot authorize another payment.</span></div><code>${challenge.grants[0].approval_id}</code>`;activeApprovalFlow=null;showToast("Approval verified, consumed, and second payment committed.")}catch(error){showToast(error.message,true)}finally{if(button.isConnected)setBusy(button,false)}}

async function runDelegationAttack(){setBusy(ui.delegationButton,true,"Evaluating authority graph…");try{const policy=readPolicy(`delegation-${Date.now()}`);const amount=Math.floor(policy.budget.monthly_limit*.6);const expires=new Date(Date.now()+3600000).toISOString();const makeGrant=(sequence,child)=>({grant_id:`${policy.policy_id}-grant-${sequence}`,parent_agent_id:"root-agent",child_agent_id:child,authority_limit:amount,expires_at:expires});const first=await api("/api/v1/demo/delegations/evaluate",{method:"POST",body:JSON.stringify({policy,grant:makeGrant(1,"buyer-a")})});const second=await api("/api/v1/demo/delegations/evaluate",{method:"POST",body:JSON.stringify({policy,grant:makeGrant(2,"buyer-b")})});ui.delegationResult.innerHTML=`<div><small>Grant 01</small><strong class="decision ${decisionClass(first.arthaniyam.decision)}">${decisionLabel(first.arthaniyam.decision)}</strong><span>${inRupees(first.delegated_total)} delegated</span></div><div><small>Grant 02 · naïve gateway</small><strong class="decision ${decisionClass(second.naive_gateway.decision)}">${decisionLabel(second.naive_gateway.decision)}</strong><span>Checks this grant alone</span></div><div><small>Grant 02 · ArthaNiyam</small><strong class="decision ${decisionClass(second.arthaniyam.decision)}">${decisionLabel(second.arthaniyam.decision)}</strong><span>${inRupees(second.delegated_total)} requested from ${inRupees(second.parent_authority)}</span></div>`;showToast("Authority multiplication attack detected.")}catch(error){showToast(error.message,true)}finally{setBusy(ui.delegationButton,false)}}

async function runRefundAttack(){setBusy(ui.refundButton,true,"Testing cumulative refunds…");try{const capabilities=await api("/api/v1/system/capabilities");if(capabilities.payment_mode!=="simulate")throw new Error("Refund Lab is disabled outside the offline simulator.");const runId=`refund-${Date.now()}`;const policy={policy_id:runId,version:1,name:"Refund conservation demo",currency:"INR",budget:{monthly_limit:5000000,per_transaction_limit:1000000},approval:{required_above:5000000,approver_count:1},vendors:{require_approved_vendor:true,allowed_vendor_ids:["vector-systems"],allowed_categories:["hardware"]},correlation:{window_hours:24,group_by:["vendor","purpose"]}};const action=paymentAction(runId,1);await api("/api/v1/runtime/evaluate",{method:"POST",body:JSON.stringify({policy,action})});await api("/api/v1/executions/orders",{method:"POST",body:JSON.stringify({policy_id:runId,policy_version:1,action_id:action.action_id})});await api("/api/v1/executions/confirm",{method:"POST",body:JSON.stringify({policy_id:runId,policy_version:1,action_id:action.action_id,simulated_outcome:"success"})});const refund=(sequence)=>api("/api/v1/demo/refunds/evaluate",{method:"POST",body:JSON.stringify({policy_id:runId,policy_version:1,action_id:action.action_id,refund_id:`${runId}-refund-${sequence}`,amount:540000,reason:"customer return demo"})});const first=await refund(1);const second=await refund(2);ui.refundResult.innerHTML=`<div><small>Refund 01 · ArthaNiyam</small><strong class="decision ${decisionClass(first.arthaniyam.decision)}">${decisionLabel(first.arthaniyam.decision)}</strong><span>${inRupees(first.refunded_after)} refunded · ${inRupees(first.remaining_refundable)} remains</span></div><div><small>Refund 02 · naïve gateway</small><strong class="decision ${decisionClass(second.naive_gateway.decision)}">${decisionLabel(second.naive_gateway.decision)}</strong><span>Compares only with original capture</span></div><div><small>Refund 02 · ArthaNiyam</small><strong class="decision ${decisionClass(second.arthaniyam.decision)}">${decisionLabel(second.arthaniyam.decision)}</strong><span>${inRupees(first.refunded_after+540000)} attempted against ${inRupees(second.captured_amount)}</span></div>`;showToast("Cumulative over-refund attack blocked.")}catch(error){showToast(error.message,true)}finally{setBusy(ui.refundButton,false)}}

async function runAdversarialEvaluation(){setBusy(ui.evaluationButton,true,"Running eleven isolated scenarios…");try{const report=await api("/api/v1/evaluations/run",{method:"POST"});const scenarios=report.scenarios.map(scenario=>`<div class="evaluation-row ${scenario.scenario_type}"><div><small>${scenario.scenario_type} · ${scenario.scenario_id.replaceAll("-"," ")}</small><strong>${scenario.invariant}</strong><span>${scenario.attack}</span></div><div><small>Expected</small><strong>${scenario.expected_outcome}</strong></div><div><small>ArthaNiyam</small><strong class="decision ${decisionClass(scenario.arthaniyam_decision)}">${decisionLabel(scenario.arthaniyam_decision)}</strong><code>${scenario.reason_code}</code></div></div>`).join("");ui.evaluationResult.innerHTML=`<div class="evaluation-summary"><div><small>Attack recall</small><strong>${report.attack_recall_percent}%</strong><span>${report.attacks_caught}/${report.attack_scenarios} caught</span></div><div><small>False-positive rate</small><strong>${report.false_positive_rate_percent}%</strong><span>${report.benign_allowed}/${report.benign_scenarios} controls allowed</span></div><div><small>Suite accuracy</small><strong>${report.accuracy_percent}%</strong><span>${report.total_scenarios} fixed scenarios</span></div><div class="evaluation-hash"><small>Canonical evidence</small><code>${report.evidence_hash}</code><span>Run ${report.run_id}</span></div></div><div class="evaluation-rows">${scenarios}</div>`;showToast(`Evaluation complete: ${report.attacks_caught}/${report.attack_scenarios} attacks caught, ${report.false_positives} false positives.`)}catch(error){showToast(error.message,true)}finally{setBusy(ui.evaluationButton,false)}}

async function runJudgeScorecard(){setBusy(ui.judgeButton,true,"Running solver + benchmarks…");try{const report=await api("/api/v1/evaluations/judge-scorecards/run",{method:"POST",body:JSON.stringify({seed:2026,samples_per_class:5})});activeJudgeScorecard=report.scorecard_id;const checks=report.checks.map(check=>`<div class="judge-check ${check.passed?"passed":"failed"}"><span>${check.passed?"✓":"!"}</span><div><strong>${check.label}</strong><small>${check.result}</small></div></div>`).join("");const limitations=report.limitations.map(item=>`<li>${item}</li>`).join("");ui.judgeResult.innerHTML=`<div class="judge-verdict ${report.verdict}"><div><small>Buildathon evidence verdict</small><strong>${report.verdict.replaceAll("_"," ")}</strong><span>${report.checks_passed}/${report.total_checks} checks passed</span></div><div><small>Test cases</small><strong>${report.total_test_cases}</strong><span>${report.fixed_scenarios} fixed + ${report.generated_cases} generated</span></div><div><small>Attack recall</small><strong>${report.attack_recall_percent}%</strong><span>Worst of both suites</span></div><div><small>False positives</small><strong>${report.false_positive_rate_percent}%</strong><span>Worst of both suites</span></div></div><div class="judge-body"><div class="judge-checks">${checks}</div><aside class="judge-limitations"><strong>Honest boundary</strong><ul>${limitations}</ul></aside></div><div class="judge-evidence"><div><code>${report.evidence_hash}</code><span>Persisted scorecard ${report.scorecard_id}</span></div><button class="button button-secondary" type="button" data-download-judge>Download verifiable JSON</button></div>`;showToast(`Judge scorecard: ${report.checks_passed}/${report.total_checks} checks passed across ${report.total_test_cases} cases.`)}catch(error){showToast(error.message,true)}finally{setBusy(ui.judgeButton,false)}}

async function downloadJudgeScorecard(button){if(!activeJudgeScorecard)return;setBusy(button,true,"Exporting…");try{const bundle=await api(`/api/v1/evaluations/judge-scorecards/${encodeURIComponent(activeJudgeScorecard)}/evidence-bundle`);const blob=new Blob([JSON.stringify(bundle,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`arthaniyam-judge-scorecard-${activeJudgeScorecard}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);showToast(`Judge evidence exported: ${bundle.bundle_hash.slice(0,24)}…`)}catch(error){showToast(error.message,true)}finally{setBusy(button,false)}}

async function runBoundaryCampaign(){const seed=Number(document.querySelector("#campaign-seed").value);const samples=Number(document.querySelector("#campaign-samples").value);setBusy(ui.boundaryButton,true,`Generating ${samples*4} boundary cases…`);try{const report=await api("/api/v1/evaluations/boundary-campaigns/run",{method:"POST",body:JSON.stringify({seed,samples_per_class:samples})});const failures=report.cases.filter(item=>!item.passed);const failureMarkup=failures.length?`<div class="campaign-failures">${failures.slice(0,8).map(item=>`<code>${item.case_id} · expected ${item.expected_blocked?"blocked":"allowed"}, got ${decisionLabel(item.decision)}</code>`).join("")}</div>`:`<div class="campaign-clean">✓ Every generated boundary case matched the independent oracle.</div>`;ui.campaignResult.innerHTML=`<div class="campaign-metrics"><div><small>Cases passed</small><strong>${report.passed_cases}/${report.total_cases}</strong></div><div><small>Attack recall</small><strong>${report.attack_recall_percent}%</strong></div><div><small>False positives</small><strong>${report.false_positive_rate_percent}%</strong></div><div><small>Throughput</small><strong>${report.throughput_per_second}/s</strong></div></div>${failureMarkup}<div class="campaign-evidence"><code>${report.evidence_hash}</code><span>Seed ${report.seed} · campaign ${report.campaign_id} · ${report.duration_ms} ms</span></div>`;showToast(`Boundary campaign passed ${report.passed_cases}/${report.total_cases} cases.`)}catch(error){showToast(error.message,true)}finally{setBusy(ui.boundaryButton,false)}}

function decisionClass(decision){if(decision==="allow"||decision==="allow_and_reserve")return"allow";if(decision==="require_approval")return"review";return"deny"}
function decisionLabel(decision){return decision.replaceAll("_"," ")}
function renderComparison(results){
  const rows=results.map((result,index)=>`<div class="comparison-row"><div><small>Request</small><strong>0${index+1} · ${inRupees(900000)}</strong></div><div><span class="decision ${decisionClass(result.naive_gateway.decision)}">${decisionLabel(result.naive_gateway.decision)}</span><span class="reason-text">${result.naive_gateway.explanation}</span></div><div><span class="decision ${decisionClass(result.arthaniyam.decision)}">${decisionLabel(result.arthaniyam.decision)}</span><span class="reason-text">${result.arthaniyam.explanation}</span></div><div><small>Correlated total</small><strong>${inRupees(result.correlated_amount)}</strong></div></div>`).join("");
  ui.comparison.innerHTML=`<div class="comparison-head"><span>Request</span><span>Naive gateway</span><span>ArthaNiyam</span><span>Shared state</span></div>${rows}`;
}

function renderExecution(execution,confirmation){const order=execution.order;ui.executionReceipt.classList.add("executed");ui.executionReceipt.innerHTML=`<span class="receipt-icon">✓</span><div><small>${order.provider} · ${order.mode} mode · ${confirmation.status.replaceAll("_"," ")}</small><strong>Verified payment ${confirmation.payment_id} for ${inRupees(order.amount)}</strong></div><code>${order.order_id}</code>`}

async function loadRazorpayCheckout(){if(window.Razorpay)return;await new Promise((resolve,reject)=>{const script=document.createElement("script");script.src="https://checkout.razorpay.com/v1/checkout.js";script.onload=resolve;script.onerror=()=>reject(new Error("Razorpay Checkout could not be loaded."));document.head.appendChild(script)})}
async function confirmWithRazorpay(execution,policy,actionId){await loadRazorpayCheckout();const checkoutResponse=await new Promise((resolve,reject)=>{const checkout=new window.Razorpay({key:execution.checkout_key_id,amount:execution.order.amount,currency:"INR",name:"ArthaNiyam",description:"Policy-approved autonomous payment",order_id:execution.order.order_id,theme:{color:"#11120f"},handler:resolve,modal:{ondismiss:()=>reject(new Error("Razorpay Test Checkout was dismissed."))}});checkout.open()});return api("/api/v1/executions/confirm",{method:"POST",body:JSON.stringify({policy_id:policy.policy_id,policy_version:1,action_id:actionId,razorpay_payment_id:checkoutResponse.razorpay_payment_id,razorpay_order_id:checkoutResponse.razorpay_order_id,razorpay_signature:checkoutResponse.razorpay_signature})})}

function renderRuntime(runtimeState,monthlyLimit){
  const state=runtimeState.state;const used=state.reserved_amount+state.committed_amount;const percent=monthlyLimit?Math.min(100,used/monthlyLimit*100):0;
  ui.availableBudget.textContent=`${inRupees(state.available_budget)} available`;ui.availableAmount.textContent=inRupees(state.available_budget);ui.reservedAmount.textContent=inRupees(state.reserved_amount);ui.committedAmount.textContent=inRupees(state.committed_amount);ui.budgetProgress.style.width=`${percent}%`;ui.eventCount.textContent=`${runtimeState.audit_trail.length} events`;
  ui.auditList.innerHTML=runtimeState.audit_trail.slice().reverse().map(event=>`<div class="audit-event"><time>${new Date(event.occurred_at).toLocaleTimeString("en-IN")}</time><div><strong>${decisionLabel(event.decision)}</strong><br/><span>${event.reason_codes.join(" · ")}</span></div><code>${event.event_id.slice(0,8)}</code></div>`).join("");
}

ui.guidedButton.addEventListener("click",runGuidedDemo);ui.compileButton.addEventListener("click",compilePolicy);ui.verifyButton.addEventListener("click",verifyPolicy);ui.rolloutButton.addEventListener("click",runPolicyRollout);ui.runButton.addEventListener("click",runAttack);ui.delegationButton.addEventListener("click",runDelegationAttack);ui.refundButton.addEventListener("click",runRefundAttack);ui.judgeButton.addEventListener("click",runJudgeScorecard);ui.evaluationButton.addEventListener("click",runAdversarialEvaluation);ui.boundaryButton.addEventListener("click",runBoundaryCampaign);ui.auditButton.addEventListener("click",runAuditIntegrity);ui.evidenceButton.addEventListener("click",downloadAuditEvidence);ui.judgeResult.addEventListener("click",event=>{const button=event.target.closest("[data-download-judge]");if(button)downloadJudgeScorecard(button)});ui.proofResult.addEventListener("click",event=>{const button=event.target.closest("[data-replay-proof]");if(button)replayProof(button)});ui.approvalConsole.addEventListener("click",event=>{const button=event.target.closest("[data-approve-challenge]");if(button)approveChallenge(button)});checkHealth();
